---
- name: Configure Ingress for Kubernetes services
  hosts: controller
  become: yes
  tasks:
    # - name: Verify Prometheus service exists
    #   k8s_info:
    #     api_version: v1
    #     kind: Service
    #     namespace: default
    #     name: prometheus-server
    #   register: prometheus_service
    #   failed_when: prometheus_service.resources | length == 0

    # - name: Verify Grafana service exists
    #   k8s_info:
    #     api_version: v1
    #     kind: Service
    #     namespace: default
    #     name: grafana
    #   register: grafana_service
    #   failed_when: grafana_service.resources | length == 0

    # - name: Verify Kubernetes Dashboard service exists
    #   k8s_info:
    #     api_version: v1
    #     kind: Service
    #     namespace: kubernetes-dashboard
    #     name: kubernetes-dashboard
    #   register: dashboard_service
    #   failed_when: dashboard_service.resources | length == 0

    - name: Create Ingress for Prometheus
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: prometheus-ingress
            namespace: default
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: prometheus.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: prometheus-server
                      port:
                        number: 80

    - name: Create Ingress for Grafana
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: grafana-ingress
            namespace: default
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: grafana.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: grafana
                      port:
                        number: 80

    - name: Create Ingress for Kubernetes Dashboard
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: kubernetes-dashboard-ingress
            namespace: kubernetes-dashboard
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: dashboard.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubernetes-dashboard
                      port:
                        number: 80
