---
- name: Install Helm
  hosts: controller
  become: yes
  vars:
    helm_version: "v3.14.0"

  tasks:
    - name: Download Helm
      get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: /tmp/helm-{{ helm_version }}-linux-amd64.tar.gz
        creates: /tmp/helm-{{ helm_version }}-linux-amd64.tar.gz

    - name: Extract Helm archive
      unarchive:
        src: /tmp/helm-{{ helm_version }}-linux-amd64.tar.gz
        dest: /tmp/helm-{{ helm_version }}
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /tmp/helm-{{ helm_version }}/helm

    - name: Move Helm binary to /usr/local/bin
      command: mv /tmp/helm-{{ helm_version }}/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Initialize Helm
      command: helm repo add stable https://charts.helm.sh/stable && helm repo update
