version: '1'
services:
  web:
    build: ./app
    image: app
    ports:
      - "5000:5000"
    networks:
      - mynetwork
  api:
    build: ./model-service
    image: model-service
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
