version: '1'
services:
  app:
    build: ./app
    image: app
    ports:
      - "5000:5000"
    networks:
      - mynetwork
  model-service:
    build: ./model-service
    image: model-service
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
