version: '1'
services:
  app:
    image: ghcr.io/remla24-team10/app:latest
    container_name: app
    ports:
      - "5000:5000"
    networks:
      - mynetwork

    environment:
      - FLASK_ENV=development
  model-service:
    image: ghcr.io/remla24-team10/model-service:latest
    container_name: model-service
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - ./model-service/model_service:/model-service/model_service
    environment:
      - FLASK_ENV=development
networks:
  mynetwork:
    driver: bridge
