apiVersion: v1
kind: Namespace
metadata:
  name: operation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: operation
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: remilejeune/app
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: operation
spec:
  selector:
    app: app
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
  namespace: operation
  labels:
    app: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model-service
        image: remilejeune/model-service
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: operation
spec:
  selector:
    app: model-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: operation
spec:
  defaultBackend:
    service:
      name: app-service
      port:
        number: 5000

