# controller main
- include_tasks: ../docker.yml

- name: Install k3d on controller
  shell: |
    curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

- name: Create k3d cluster
  become: yes
  shell: |
    k3d cluster create mycluster --agents 2 --api-port 6443 --port 80:80@loadbalancer --k3s-arg "--disable=traefik@server:0"
  environment:
    K3S_NODE_NAME: "controller"


- name: Ensure k3d cluster is running
  shell: |
    k3d cluster list
  register: k3d_status

- name: Set k3d cluster fact
  set_fact:
    k3d_status: "{{ k3d_status.stdout }}"


- name: install kubectl
  become: yes
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Create .kube directory
  file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Get kubeconfig
  shell: |
    mkdir ~/.kube
    mkdir ~/.kube/config
    k3d kubeconfig get mycluster > ~/.kube/config
  register: kubeconfig

- name: Add Helm repositories
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo add grafana https://grafana.github.io/helm-charts
    helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
    helm repo update

- name: Install Prometheus
  shell: |
    helm install prometheus prometheus-community/prometheus --version 25.12.0 --namespace monitoring --create-namespace

- name: Install Grafana
  shell: |
    helm install grafana grafana/grafana --namespace monitoring --create-namespace
    
- name: Install Kubernetes Dashboard
  shell: |
    helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace kube-system --create-namespace
    
- name: Display kubeconfig for local use
  shell: cat ~/.kube/config
  register: local_kubeconfig
  delegate_to: localhost
  run_once: true

- debug:
    msg: "{{ local_kubeconfig.stdout }}"
      
    
 