- name: Update apt package index
  apt:
    update_cache: yes
  register: apt_update
  until: apt_update is succeeded

- name: Install Docker dependencies
  apt:
    name:
      - ca-certificates
      - curl
  register: docker_deps
  until: docker_deps is succeeded

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  register: download_docker_key
  until: download_docker_key is succeeded

- name: Add Docker apt repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  register: add_docker_repo
  until: add_docker_repo is succeeded

- name: Update apt package index again
  apt:
    update_cache: yes
  register: apt_update_again
  until: apt_update_again is succeeded

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  register: docker_install
  until: docker_install is succeeded

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
